# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_ozqFo-mlzYSwm1Eep40Sw7cXvhlx-9L
"""

def Noutbuk_Narxi(belgi):
    if belgi == "Asus":
        return "minimum 500$ - 4000$"
    elif belgi == "Macbook":
        return "300$ - 2600$"
    elif belgi == "Acer":
        return "320$ - 1100$"
    elif belgi == "Victus":
        return "220$ - 1300$"
    elif belgi == "MSI":
        return "620$ - 1820$"
    elif belgi == "Lenovo":
        return "320$ - 1320$"
    elif belgi == "Gigabyte":
        return "720$ - 1450$"
    elif belgi == "Dell":
        return "170$ - 520$"
    else:
        return "Kompyuter do'konlariga yoki online do'kolariga murojaat qiling "

belgi = input("Kompyuter Modellari: ")
natija =Noutbuk_Narxi(belgi)
print(natija)